// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.LinkedIn.OpenApiClient.LearningActivityReports.V2;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.LearningActivityReports
{
    /// <summary>
    /// Builds and executes requests for operations under \learning-activity-reports
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LearningActivityReportsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The v2 property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.LearningActivityReports.V2.V2RequestBuilder V2
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.LearningActivityReports.V2.V2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.LearningActivityReports.LearningActivityReportsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LearningActivityReportsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/learning-activity-reports", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.LearningActivityReports.LearningActivityReportsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LearningActivityReportsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/learning-activity-reports", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
