// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.LinkedIn.OpenApiClient.Audiences.AdAccounts;
using Soenneker.LinkedIn.OpenApiClient.Audiences.DmpSegments;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Audiences
{
    /// <summary>
    /// Builds and executes requests for operations under \audiences
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AudiencesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The adAccounts property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.Audiences.AdAccounts.AdAccountsRequestBuilder AdAccounts
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.Audiences.AdAccounts.AdAccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dmpSegments property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.Audiences.DmpSegments.DmpSegmentsRequestBuilder DmpSegments
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.Audiences.DmpSegments.DmpSegmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Audiences.AudiencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AudiencesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/audiences", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Audiences.AudiencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AudiencesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/audiences", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
