// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.Urn3Ali3AmediaPlan3A123456;
using Soenneker.LinkedIn.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans
{
    /// <summary>
    /// Builds and executes requests for operations under \media-planning\mediaPlans
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaPlansRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The urn3Ali3AmediaPlan3A123456 property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.Urn3Ali3AmediaPlan3A123456.Urn3Ali3AmediaPlan3A123456RequestBuilder Urn3Ali3AmediaPlan3A123456
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.Urn3Ali3AmediaPlan3A123456.Urn3Ali3AmediaPlan3A123456RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaPlansRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media-planning/mediaPlans{?accountUrn*,forecastMetricType*,q*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaPlansRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media-planning/mediaPlans{?accountUrn*,forecastMetricType*,q*}", rawUrl)
        {
        }
        /// <summary>
        /// Fetch all Media Plans in an Ad Account
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder.MediaPlansRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder.MediaPlansRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200Response>(requestInfo, global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a Media Plan
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningCreateAMediaPlanRequest body, Action<RequestConfiguration<global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder.MediaPlansRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningCreateAMediaPlanRequest body, Action<RequestConfiguration<global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder.MediaPlansRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch all Media Plans in an Ad Account
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder.MediaPlansRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder.MediaPlansRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a Media Plan
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningCreateAMediaPlanRequest body, Action<RequestConfiguration<global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder.MediaPlansRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningCreateAMediaPlanRequest body, Action<RequestConfiguration<global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder.MediaPlansRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.LinkedIn.OpenApiClient.MediaPlanning.MediaPlans.MediaPlansRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Fetch all Media Plans in an Ad Account
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MediaPlansRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("accountUrn")]
            public string? AccountUrn { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("accountUrn")]
            public string AccountUrn { get; set; }
            #pragma warning restore CS1591
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("q")]
            public string? Q { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("q")]
            public string Q { get; set; }
            #pragma warning restore CS1591
#endif
        }
        /// <summary>
        /// Create a Media Plan
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MediaPlansRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("forecastMetricType")]
            public string? ForecastMetricType { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("forecastMetricType")]
            public string ForecastMetricType { get; set; }
            #pragma warning restore CS1591
#endif
        }
    }
}
#pragma warning restore CS0618
