// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ApplicationInterviewFeedbacks;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ApplicationNotes;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ApplicationStage;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.AtsApplications;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.Attachments;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.CandidateNotes;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.Candidates;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.EntityAclAssignees;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.EntityAcls;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ExportedCandidates;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.IntegrationConfigurations;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.Integrations;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.JobRequisitionStages;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.JobRequisitions;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.MailStubs;
using Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.SeatsV2;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest
{
    /// <summary>
    /// Builds and executes requests for operations under \recruiter-system-connect-versioned\rest
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The applicationInterviewFeedbacks property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ApplicationInterviewFeedbacks.ApplicationInterviewFeedbacksRequestBuilder ApplicationInterviewFeedbacks
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ApplicationInterviewFeedbacks.ApplicationInterviewFeedbacksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The applicationNotes property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ApplicationNotes.ApplicationNotesRequestBuilder ApplicationNotes
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ApplicationNotes.ApplicationNotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The applicationStage property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ApplicationStage.ApplicationStageRequestBuilder ApplicationStage
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ApplicationStage.ApplicationStageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The atsApplications property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.AtsApplications.AtsApplicationsRequestBuilder AtsApplications
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.AtsApplications.AtsApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The attachments property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.Attachments.AttachmentsRequestBuilder Attachments
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.Attachments.AttachmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The candidateNotes property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.CandidateNotes.CandidateNotesRequestBuilder CandidateNotes
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.CandidateNotes.CandidateNotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The candidates property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.Candidates.CandidatesRequestBuilder Candidates
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.Candidates.CandidatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The entityAclAssignees property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.EntityAclAssignees.EntityAclAssigneesRequestBuilder EntityAclAssignees
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.EntityAclAssignees.EntityAclAssigneesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The entityAcls property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.EntityAcls.EntityAclsRequestBuilder EntityAcls
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.EntityAcls.EntityAclsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exportedCandidates property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ExportedCandidates.ExportedCandidatesRequestBuilder ExportedCandidates
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.ExportedCandidates.ExportedCandidatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The integrationConfigurations property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.IntegrationConfigurations.IntegrationConfigurationsRequestBuilder IntegrationConfigurations
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.IntegrationConfigurations.IntegrationConfigurationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The integrations property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.Integrations.IntegrationsRequestBuilder Integrations
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.Integrations.IntegrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobRequisitions property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.JobRequisitions.JobRequisitionsRequestBuilder JobRequisitions
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.JobRequisitions.JobRequisitionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobRequisitionStages property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.JobRequisitionStages.JobRequisitionStagesRequestBuilder JobRequisitionStages
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.JobRequisitionStages.JobRequisitionStagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mailStubs property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.MailStubs.MailStubsRequestBuilder MailStubs
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.MailStubs.MailStubsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The seatsV2 property</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.SeatsV2.SeatsV2RequestBuilder SeatsV2
        {
            get => new global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.SeatsV2.SeatsV2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.RestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/recruiter-system-connect-versioned/rest", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.RecruiterSystemConnectVersioned.Rest.RestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/recruiter-system-connect-versioned/rest", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
