// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683Action : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The organizationRoleAuthorizationAction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683ActionOrganizationRoleAuthorizationAction? OrganizationRoleAuthorizationAction { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683ActionOrganizationRoleAuthorizationAction OrganizationRoleAuthorizationAction { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683Action"/> and sets the default values.
        /// </summary>
        public PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683Action()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683Action"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683Action CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683Action();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "organizationRoleAuthorizationAction", n => { OrganizationRoleAuthorizationAction = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683ActionOrganizationRoleAuthorizationAction>(global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683ActionOrganizationRoleAuthorizationAction.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationAuthorizationsBatchget200ResponseResultsActionOrganizationRoleAuthorizationActionActionTypeAdministratorWriteImpersonationScopeValueSubjectValueMemberUrn3Ali3Aperson3AsyabJjccePOrganizationUrn3Ali3Aorganization3A10002683ActionOrganizationRoleAuthorizationAction>("organizationRoleAuthorizationAction", OrganizationRoleAuthorizationAction);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
