// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessPolicy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessPolicy { get; set; }
#nullable restore
#else
        public string AccessPolicy { get; set; }
#endif
        /// <summary>The account property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Account { get; set; }
#nullable restore
#else
        public string Account { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created property</summary>
        public int? Created { get; set; }
        /// <summary>The destinations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItemDestinationsItem>? Destinations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItemDestinationsItem> Destinations { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The inputCount property</summary>
        public int? InputCount { get; set; }
        /// <summary>The lastModified property</summary>
        public int? LastModified { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The sourcePlatform property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourcePlatform { get; set; }
#nullable restore
#else
        public string SourcePlatform { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItem"/> and sets the default values.
        /// </summary>
        public AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessPolicy", n => { AccessPolicy = n.GetStringValue(); } },
                { "account", n => { Account = n.GetStringValue(); } },
                { "created", n => { Created = n.GetIntValue(); } },
                { "destinations", n => { Destinations = n.GetCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItemDestinationsItem>(global::Soenneker.LinkedIn.OpenApiClient.Models.AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItemDestinationsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "inputCount", n => { InputCount = n.GetIntValue(); } },
                { "lastModified", n => { LastModified = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "sourcePlatform", n => { SourcePlatform = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accessPolicy", AccessPolicy);
            writer.WriteStringValue("account", Account);
            writer.WriteIntValue("created", Created);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.AudiencesOperation4FetchExistingAudiencesForChosenAdAccounts200ResponseElementsItemDestinationsItem>("destinations", Destinations);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("inputCount", InputCount);
            writer.WriteIntValue("lastModified", LastModified);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("sourcePlatform", SourcePlatform);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
