// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    /// <summary>TEXT_AD - Text-based ads that show up in the right column or top of the page on LinkedIn. SPONSORED_UPDATES - Native ads that promote a company&apos;s content updates in the LinkedIn feed. SPONSORED_INMAILS - Personalized messages with a call-to-action button delivered to a LinkedIn&apos;s member inbox. DYNAMIC - Ads that are dynamically personalized.Documented type: CampaignTypeRequirement: True</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CampaignManagementCreateACampaignGroup201ResponseType
    {
        [EnumMember(Value = "TEXT_AD")]
        #pragma warning disable CS1591
        TextAd,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPONSORED_UPDATES")]
        #pragma warning disable CS1591
        SponsoredUpdates,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPONSORED_INMAILS")]
        #pragma warning disable CS1591
        SponsoredInmails,
        #pragma warning restore CS1591
        [EnumMember(Value = "DYNAMIC")]
        #pragma warning disable CS1591
        Dynamic,
        #pragma warning restore CS1591
    }
}
