// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CampaignManagementFetchACreativeUsingCreativeId200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Account { get; set; }
#nullable restore
#else
        public string Account { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The campaign property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Campaign { get; set; }
#nullable restore
#else
        public string Campaign { get; set; }
#endif
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseContent? Content { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseContent Content { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public int? CreatedAt { get; set; }
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The intendedStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntendedStatus { get; set; }
#nullable restore
#else
        public string IntendedStatus { get; set; }
#endif
        /// <summary>The isServing property</summary>
        public bool? IsServing { get; set; }
        /// <summary>The isTest property</summary>
        public bool? IsTest { get; set; }
        /// <summary>The lastModifiedAt property</summary>
        public int? LastModifiedAt { get; set; }
        /// <summary>The lastModifiedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastModifiedBy { get; set; }
#nullable restore
#else
        public string LastModifiedBy { get; set; }
#endif
        /// <summary>The review property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseReview? Review { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseReview Review { get; set; }
#endif
        /// <summary>The servingHoldReasons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ServingHoldReasons { get; set; }
#nullable restore
#else
        public List<string> ServingHoldReasons { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200Response"/> and sets the default values.
        /// </summary>
        public CampaignManagementFetchACreativeUsingCreativeId200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account", n => { Account = n.GetStringValue(); } },
                { "campaign", n => { Campaign = n.GetStringValue(); } },
                { "content", n => { Content = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseContent>(global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseContent.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetIntValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "intendedStatus", n => { IntendedStatus = n.GetStringValue(); } },
                { "isServing", n => { IsServing = n.GetBoolValue(); } },
                { "isTest", n => { IsTest = n.GetBoolValue(); } },
                { "lastModifiedAt", n => { LastModifiedAt = n.GetIntValue(); } },
                { "lastModifiedBy", n => { LastModifiedBy = n.GetStringValue(); } },
                { "review", n => { Review = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseReview>(global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseReview.CreateFromDiscriminatorValue); } },
                { "servingHoldReasons", n => { ServingHoldReasons = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account", Account);
            writer.WriteStringValue("campaign", Campaign);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseContent>("content", Content);
            writer.WriteIntValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("intendedStatus", IntendedStatus);
            writer.WriteBoolValue("isServing", IsServing);
            writer.WriteBoolValue("isTest", IsTest);
            writer.WriteIntValue("lastModifiedAt", LastModifiedAt);
            writer.WriteStringValue("lastModifiedBy", LastModifiedBy);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CampaignManagementFetchACreativeUsingCreativeId200ResponseReview>("review", Review);
            writer.WriteCollectionOfPrimitiveValues<string>("servingHoldReasons", ServingHoldReasons);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
