// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    /// <summary>Identifies the pacing option used for the campaign.Optional and editable only on create. Possible values: LIFETIME - Lifetime pacing that optimizes campaign budget delivery throughout campaign&apos;s lifetime. ACCELERATED - Accelerated pacing is a pacing option that can maximize reach and delivery during an event as it works to deliver your campaign budget to your target audience as quickly as possible. Note: The field is only available from version 202501 and above.Documented type: stringRequirement: False</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CampaignManagementCreateCampaignSponsoredupdatesRequestElementsItemPacingStrategy
    {
        [EnumMember(Value = "LIFETIME")]
        #pragma warning disable CS1591
        Lifetime,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCELERATED")]
        #pragma warning disable CS1591
        Accelerated,
        #pragma warning restore CS1591
    }
}
