// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    /// <summary>Range of the number of staff associated with this entity. Possible values: SIZE_1 SIZE_2_TO_10 SIZE_11_TO_50 SIZE_51_TO_200 SIZE_201_TO_500 SIZE_501_TO_1000 SIZE_1001_TO_5000 SIZE_5001_TO_10000 SIZE_10001_OR_MOREDocumented type: string</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CommunityManagementRetrieveOrganizationById200ResponseStaffCountRange
    {
        [EnumMember(Value = "SIZE_1")]
        #pragma warning disable CS1591
        Size1,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIZE_2_TO_10")]
        #pragma warning disable CS1591
        Size2To10,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIZE_11_TO_50")]
        #pragma warning disable CS1591
        Size11To50,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIZE_51_TO_200")]
        #pragma warning disable CS1591
        Size51To200,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIZE_201_TO_500")]
        #pragma warning disable CS1591
        Size201To500,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIZE_501_TO_1000")]
        #pragma warning disable CS1591
        Size501To1000,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIZE_1001_TO_5000")]
        #pragma warning disable CS1591
        Size1001To5000,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIZE_5001_TO_10000")]
        #pragma warning disable CS1591
        Size5001To10000,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIZE_10001_OR_MORE")]
        #pragma warning disable CS1591
        Size10001OrMore,
        #pragma warning restore CS1591
    }
}
