// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CommunityManagementRetrieveAnAdministeredOrganizationBrand200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alternativeNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AlternativeNames { get; set; }
#nullable restore
#else
        public UntypedNode AlternativeNames { get; set; }
#endif
        /// <summary>The autoCreated property</summary>
        public bool? AutoCreated { get; set; }
        /// <summary>The defaultLocale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseDefaultLocale? DefaultLocale { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseDefaultLocale DefaultLocale { get; set; }
#endif
        /// <summary>The groups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Groups { get; set; }
#nullable restore
#else
        public UntypedNode Groups { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The industries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Industries { get; set; }
#nullable restore
#else
        public List<string> Industries { get; set; }
#endif
        /// <summary>The localizedName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalizedName { get; set; }
#nullable restore
#else
        public string LocalizedName { get; set; }
#endif
        /// <summary>The localizedSpecialties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? LocalizedSpecialties { get; set; }
#nullable restore
#else
        public UntypedNode LocalizedSpecialties { get; set; }
#endif
        /// <summary>The localizedWebsite property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalizedWebsite { get; set; }
#nullable restore
#else
        public string LocalizedWebsite { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseName? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseName Name { get; set; }
#endif
        /// <summary>The parentRelationship property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseParentRelationship? ParentRelationship { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseParentRelationship ParentRelationship { get; set; }
#endif
        /// <summary>The primaryOrganizationType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryOrganizationType { get; set; }
#nullable restore
#else
        public string PrimaryOrganizationType { get; set; }
#endif
        /// <summary>The specialties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Specialties { get; set; }
#nullable restore
#else
        public UntypedNode Specialties { get; set; }
#endif
        /// <summary>The URN property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? URN { get; set; }
#nullable restore
#else
        public string URN { get; set; }
#endif
        /// <summary>The vanityName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VanityName { get; set; }
#nullable restore
#else
        public string VanityName { get; set; }
#endif
        /// <summary>The versionTag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionTag { get; set; }
#nullable restore
#else
        public string VersionTag { get; set; }
#endif
        /// <summary>The website property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseWebsite? Website { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseWebsite Website { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200Response"/> and sets the default values.
        /// </summary>
        public CommunityManagementRetrieveAnAdministeredOrganizationBrand200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alternativeNames", n => { AlternativeNames = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "autoCreated", n => { AutoCreated = n.GetBoolValue(); } },
                { "defaultLocale", n => { DefaultLocale = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseDefaultLocale>(global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseDefaultLocale.CreateFromDiscriminatorValue); } },
                { "groups", n => { Groups = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "industries", n => { Industries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "localizedName", n => { LocalizedName = n.GetStringValue(); } },
                { "localizedSpecialties", n => { LocalizedSpecialties = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "localizedWebsite", n => { LocalizedWebsite = n.GetStringValue(); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseName>(global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseName.CreateFromDiscriminatorValue); } },
                { "parentRelationship", n => { ParentRelationship = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseParentRelationship>(global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseParentRelationship.CreateFromDiscriminatorValue); } },
                { "primaryOrganizationType", n => { PrimaryOrganizationType = n.GetStringValue(); } },
                { "specialties", n => { Specialties = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "$URN", n => { URN = n.GetStringValue(); } },
                { "vanityName", n => { VanityName = n.GetStringValue(); } },
                { "versionTag", n => { VersionTag = n.GetStringValue(); } },
                { "website", n => { Website = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseWebsite>(global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseWebsite.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("alternativeNames", AlternativeNames);
            writer.WriteBoolValue("autoCreated", AutoCreated);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseDefaultLocale>("defaultLocale", DefaultLocale);
            writer.WriteObjectValue<UntypedNode>("groups", Groups);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfPrimitiveValues<string>("industries", Industries);
            writer.WriteStringValue("localizedName", LocalizedName);
            writer.WriteObjectValue<UntypedNode>("localizedSpecialties", LocalizedSpecialties);
            writer.WriteStringValue("localizedWebsite", LocalizedWebsite);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseName>("name", Name);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseParentRelationship>("parentRelationship", ParentRelationship);
            writer.WriteStringValue("primaryOrganizationType", PrimaryOrganizationType);
            writer.WriteObjectValue<UntypedNode>("specialties", Specialties);
            writer.WriteStringValue("$URN", URN);
            writer.WriteStringValue("vanityName", VanityName);
            writer.WriteStringValue("versionTag", VersionTag);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.CommunityManagementRetrieveAnAdministeredOrganizationBrand200ResponseWebsite>("website", Website);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
