// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ContentApisGetInMailContentDefaultResponse : ApiException, IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Documented type: SponsoredAccount URNRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Account { get; set; }
#nullable restore
#else
        public string Account { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Documented type: TimeRequirement: (Read-Only) Yes</summary>
        public long? CreatedAt { get; set; }
        /// <summary>Documented type: URNRequirement: (Read-Only) Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Documented type: stringRequirement: No</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomFooter { get; set; }
#nullable restore
#else
        public string CustomFooter { get; set; }
#endif
        /// <summary>Documented type: stringRequirement: No</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HtmlBody { get; set; }
#nullable restore
#else
        public string HtmlBody { get; set; }
#endif
        /// <summary>Documented type: AdInMailContent URNRequirement: (Read-Only) Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Documented type: TimeRequirement: (Read-Only) Yes</summary>
        public long? LastModifiedAt { get; set; }
        /// <summary>Documented type: URNRequirement: (Read-Only) Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastModifiedBy { get; set; }
#nullable restore
#else
        public string LastModifiedBy { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>Documented type: stringRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Documented type: URNRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sender { get; set; }
#nullable restore
#else
        public string Sender { get; set; }
#endif
        /// <summary>Documented type: AdInMailRegularSubContent, AdInMailGuidedRepliesSubContent, or AdInMailFormSubContent,Requirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.ContentApisGetInMailContentDefaultResponseSubContent? SubContent { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.ContentApisGetInMailContentDefaultResponseSubContent SubContent { get; set; }
#endif
        /// <summary>Documented type: stringRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.ContentApisGetInMailContentDefaultResponse"/> and sets the default values.
        /// </summary>
        public ContentApisGetInMailContentDefaultResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.ContentApisGetInMailContentDefaultResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.ContentApisGetInMailContentDefaultResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.ContentApisGetInMailContentDefaultResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account", n => { Account = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetLongValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "customFooter", n => { CustomFooter = n.GetStringValue(); } },
                { "htmlBody", n => { HtmlBody = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastModifiedAt", n => { LastModifiedAt = n.GetLongValue(); } },
                { "lastModifiedBy", n => { LastModifiedBy = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "sender", n => { Sender = n.GetStringValue(); } },
                { "subContent", n => { SubContent = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.ContentApisGetInMailContentDefaultResponseSubContent>(global::Soenneker.LinkedIn.OpenApiClient.Models.ContentApisGetInMailContentDefaultResponseSubContent.CreateFromDiscriminatorValue); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account", Account);
            writer.WriteLongValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("customFooter", CustomFooter);
            writer.WriteStringValue("htmlBody", HtmlBody);
            writer.WriteStringValue("id", Id);
            writer.WriteLongValue("lastModifiedAt", LastModifiedAt);
            writer.WriteStringValue("lastModifiedBy", LastModifiedBy);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("sender", Sender);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.ContentApisGetInMailContentDefaultResponseSubContent>("subContent", SubContent);
            writer.WriteStringValue("subject", Subject);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
