// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConversionsApiOperation7DBatchAssociateMultipleCampaignsToConversionRuleRequestEntitiesCampaignUrn3Ali3AsponsoredCampaign3ACampaignIdConversionUrn3Alla3AllaPartnerConversion3AConversionId : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The campaign property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Campaign { get; set; }
#nullable restore
#else
        public string Campaign { get; set; }
#endif
        /// <summary>The conversion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Conversion { get; set; }
#nullable restore
#else
        public string Conversion { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.ConversionsApiOperation7DBatchAssociateMultipleCampaignsToConversionRuleRequestEntitiesCampaignUrn3Ali3AsponsoredCampaign3ACampaignIdConversionUrn3Alla3AllaPartnerConversion3AConversionId"/> and sets the default values.
        /// </summary>
        public ConversionsApiOperation7DBatchAssociateMultipleCampaignsToConversionRuleRequestEntitiesCampaignUrn3Ali3AsponsoredCampaign3ACampaignIdConversionUrn3Alla3AllaPartnerConversion3AConversionId()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.ConversionsApiOperation7DBatchAssociateMultipleCampaignsToConversionRuleRequestEntitiesCampaignUrn3Ali3AsponsoredCampaign3ACampaignIdConversionUrn3Alla3AllaPartnerConversion3AConversionId"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.ConversionsApiOperation7DBatchAssociateMultipleCampaignsToConversionRuleRequestEntitiesCampaignUrn3Ali3AsponsoredCampaign3ACampaignIdConversionUrn3Alla3AllaPartnerConversion3AConversionId CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.ConversionsApiOperation7DBatchAssociateMultipleCampaignsToConversionRuleRequestEntitiesCampaignUrn3Ali3AsponsoredCampaign3ACampaignIdConversionUrn3Alla3AllaPartnerConversion3AConversionId();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "campaign", n => { Campaign = n.GetStringValue(); } },
                { "conversion", n => { Conversion = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("campaign", Campaign);
            writer.WriteStringValue("conversion", Conversion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
