// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LearnMarketingLeadSyncLeadSyncSchemaLeadgenformreviewstatusSubObject
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        Rejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "PREAPPROVED")]
        #pragma warning disable CS1591
        Preapproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTO_APPROVED")]
        #pragma warning disable CS1591
        AutoApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEEDS_REVIEW")]
        #pragma warning disable CS1591
        NeedsReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTO_REJECTED")]
        #pragma warning disable CS1591
        AutoRejected,
        #pragma warning restore CS1591
    }
}
