// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    /// <summary>
    /// The field that contains the favorable multiple choice answer value for this question. This should only be present for which the question has a preferred/required qualification.Documented type: FavorableMultipleChoiceAnswerRequirement: No
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LearnTalentApplyConnectOnsiteApplyConfigurationSchemaMultiplechoicequestiondetailsFieldsFavorableMultipleChoiceAnswer : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The symbolicNames from MultipleChoiceQuestionDetails that should be considered favorable. An example could be [“BACHELOR”, “MASTERS”] to indicate that the job poster wants the candidate to have either one of the educational levels.Documented type: String[]Requirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FavorableSymbolicNames { get; set; }
#nullable restore
#else
        public List<string> FavorableSymbolicNames { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.LearnTalentApplyConnectOnsiteApplyConfigurationSchemaMultiplechoicequestiondetailsFieldsFavorableMultipleChoiceAnswer"/> and sets the default values.
        /// </summary>
        public LearnTalentApplyConnectOnsiteApplyConfigurationSchemaMultiplechoicequestiondetailsFieldsFavorableMultipleChoiceAnswer()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.LearnTalentApplyConnectOnsiteApplyConfigurationSchemaMultiplechoicequestiondetailsFieldsFavorableMultipleChoiceAnswer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.LearnTalentApplyConnectOnsiteApplyConfigurationSchemaMultiplechoicequestiondetailsFieldsFavorableMultipleChoiceAnswer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.LearnTalentApplyConnectOnsiteApplyConfigurationSchemaMultiplechoicequestiondetailsFieldsFavorableMultipleChoiceAnswer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "favorableSymbolicNames", n => { FavorableSymbolicNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("favorableSymbolicNames", FavorableSymbolicNames);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
