// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LearningActivityReportsLearningActivityReports200ResponseElementsItemActivitiesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assetType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssetType { get; set; }
#nullable restore
#else
        public string AssetType { get; set; }
#endif
        /// <summary>The engagementMetricQualifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EngagementMetricQualifier { get; set; }
#nullable restore
#else
        public string EngagementMetricQualifier { get; set; }
#endif
        /// <summary>The engagementType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EngagementType { get; set; }
#nullable restore
#else
        public string EngagementType { get; set; }
#endif
        /// <summary>The engagementValue property</summary>
        public int? EngagementValue { get; set; }
        /// <summary>The firstEngagedAt property</summary>
        public int? FirstEngagedAt { get; set; }
        /// <summary>The lastEngagedAt property</summary>
        public int? LastEngagedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.LearningActivityReportsLearningActivityReports200ResponseElementsItemActivitiesItem"/> and sets the default values.
        /// </summary>
        public LearningActivityReportsLearningActivityReports200ResponseElementsItemActivitiesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.LearningActivityReportsLearningActivityReports200ResponseElementsItemActivitiesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.LearningActivityReportsLearningActivityReports200ResponseElementsItemActivitiesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.LearningActivityReportsLearningActivityReports200ResponseElementsItemActivitiesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assetType", n => { AssetType = n.GetStringValue(); } },
                { "engagementMetricQualifier", n => { EngagementMetricQualifier = n.GetStringValue(); } },
                { "engagementType", n => { EngagementType = n.GetStringValue(); } },
                { "engagementValue", n => { EngagementValue = n.GetIntValue(); } },
                { "firstEngagedAt", n => { FirstEngagedAt = n.GetIntValue(); } },
                { "lastEngagedAt", n => { LastEngagedAt = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assetType", AssetType);
            writer.WriteStringValue("engagementMetricQualifier", EngagementMetricQualifier);
            writer.WriteStringValue("engagementType", EngagementType);
            writer.WriteIntValue("engagementValue", EngagementValue);
            writer.WriteIntValue("firstEngagedAt", FirstEngagedAt);
            writer.WriteIntValue("lastEngagedAt", LastEngagedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
