// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    /// <summary>
    /// If present, the details about the learning asset. If this field is not present, it means the request did not specify retrieving the asset details (see the &quot;Specifying the level of asset details&quot; section).Documented type: AssetDetailsRequirement: No
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LearningContentLearningAssetsByCriteriaFinder200ResponseAnyOf8ElementsItemDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The availability of the learning asset.Documented type: AvailabilityRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsAvailability? Availability { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsAvailability Availability { get; set; }
#endif
        /// <summary>The locales the learning asset is available in.Documented type: Locale []Requirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsLocale>? AvailableLocales { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsLocale> AvailableLocales { get; set; }
#endif
        /// <summary>The learning classifications the learning asset is tagged with.Documented type: AssetClassification []Requirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetclassification>? Classifications { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetclassification> Classifications { get; set; }
#endif
        /// <summary>The contributors involved in the lifecycle of the learning asset - for example, authors or publishers.Documented type: Contributor []Requirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsContributor>? Contributors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsContributor> Contributors { get; set; }
#endif
        /// <summary>Indicates whether the learning asset was curated for Learning Management System consumption by an account administrator in LinkedIn Learning. Currently applies only to video assetsDocumented type: BooleanRequirement: No</summary>
        public bool? CuratedForLearningManagementSystem { get; set; }
        /// <summary>If present, the text-only description of the learning asset, localized if available. Any HTML markup will be stripped from this description.Documented type: LocaleStringRequirement: No</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescription? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescription Description { get; set; }
#endif
        /// <summary>If present, the description - including any HTML markup - of the learning asset, localized if available.Documented type: LocaleStringRequirement: No</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescriptionIncludingHtml? DescriptionIncludingHtml { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescriptionIncludingHtml DescriptionIncludingHtml { get; set; }
#endif
        /// <summary>The images that can be used to represent the learning asset.Documented type: AssetImagesRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsImages? Images { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsImages Images { get; set; }
#endif
        /// <summary>The epoch time in milliseconds indicating when the learning asset was last updated.Documented type: TimeRequirement: Yes</summary>
        public long? LastUpdatedAt { get; set; }
        /// <summary>If present, the difficulty level of the learning asset.Documented type: DifficultyLevelRequirement: No</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsLevel? Level { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsLevel Level { get; set; }
#endif
        /// <summary>The epoch time in milliseconds indicating when the learning asset was published.Documented type: TimeRequirement: Yes</summary>
        public long? PublishedAt { get; set; }
        /// <summary>The value of this field is currently always an empty array. Future versions of the API may use this field to indicate relationships the learning asset has to other learning assets.Documented type: ArrayRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsRelationshipsItem>? Relationships { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsRelationshipsItem> Relationships { get; set; }
#endif
        /// <summary>If present, the epoch time in milliseconds indicating when the learning asset was retired.Documented type: TimeRequirement: No</summary>
        public long? RetiredAt { get; set; }
        /// <summary>Localized text only short description of the learning asset.Documented type: LocaleStringRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsShortDescription? ShortDescription { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsShortDescription ShortDescription { get; set; }
#endif
        /// <summary>If present, the time span indicating how long the learning asset takes to complete.Documented type: TimeSpanRequirement: No</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsTimeToComplete? TimeToComplete { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsTimeToComplete TimeToComplete { get; set; }
#endif
        /// <summary>The URLs that can be used to launch the learning asset.Documented type: AssetUrlsRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsUrls? Urls { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsUrls Urls { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.LearningContentLearningAssetsByCriteriaFinder200ResponseAnyOf8ElementsItemDetails"/> and sets the default values.
        /// </summary>
        public LearningContentLearningAssetsByCriteriaFinder200ResponseAnyOf8ElementsItemDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.LearningContentLearningAssetsByCriteriaFinder200ResponseAnyOf8ElementsItemDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.LearningContentLearningAssetsByCriteriaFinder200ResponseAnyOf8ElementsItemDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.LearningContentLearningAssetsByCriteriaFinder200ResponseAnyOf8ElementsItemDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availability", n => { Availability = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsAvailability>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsAvailability.CreateFromDiscriminatorValue); } },
                { "availableLocales", n => { AvailableLocales = n.GetCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsLocale>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsLocale.CreateFromDiscriminatorValue)?.AsList(); } },
                { "classifications", n => { Classifications = n.GetCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetclassification>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetclassification.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contributors", n => { Contributors = n.GetCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsContributor>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsContributor.CreateFromDiscriminatorValue)?.AsList(); } },
                { "curatedForLearningManagementSystem", n => { CuratedForLearningManagementSystem = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescription>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescription.CreateFromDiscriminatorValue); } },
                { "descriptionIncludingHtml", n => { DescriptionIncludingHtml = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescriptionIncludingHtml>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescriptionIncludingHtml.CreateFromDiscriminatorValue); } },
                { "images", n => { Images = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsImages>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsImages.CreateFromDiscriminatorValue); } },
                { "lastUpdatedAt", n => { LastUpdatedAt = n.GetLongValue(); } },
                { "level", n => { Level = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsLevel>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsLevel.CreateFromDiscriminatorValue); } },
                { "publishedAt", n => { PublishedAt = n.GetLongValue(); } },
                { "relationships", n => { Relationships = n.GetCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsRelationshipsItem>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsRelationshipsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "retiredAt", n => { RetiredAt = n.GetLongValue(); } },
                { "shortDescription", n => { ShortDescription = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsShortDescription>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsShortDescription.CreateFromDiscriminatorValue); } },
                { "timeToComplete", n => { TimeToComplete = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsTimeToComplete>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsTimeToComplete.CreateFromDiscriminatorValue); } },
                { "urls", n => { Urls = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsUrls>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsUrls.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsAvailability>("availability", Availability);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsLocale>("availableLocales", AvailableLocales);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetclassification>("classifications", Classifications);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsContributor>("contributors", Contributors);
            writer.WriteBoolValue("curatedForLearningManagementSystem", CuratedForLearningManagementSystem);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescription>("description", Description);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsDescriptionIncludingHtml>("descriptionIncludingHtml", DescriptionIncludingHtml);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsImages>("images", Images);
            writer.WriteLongValue("lastUpdatedAt", LastUpdatedAt);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsLevel>("level", Level);
            writer.WriteLongValue("publishedAt", PublishedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsRelationshipsItem>("relationships", Relationships);
            writer.WriteLongValue("retiredAt", RetiredAt);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsShortDescription>("shortDescription", ShortDescription);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsTimeToComplete>("timeToComplete", TimeToComplete);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnLearningReferenceLearningassetsAssetdetailsUrls>("urls", Urls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
