// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    /// <summary>Specifies the type of feed distribution. Does not distribute to feed when missing. Can be the following values: NONE- Do not distribute within LinkedIn via feed. MAIN_FEED- Distribute to the flagship feed, and container entity feed if applicable. CONTAINER_ONLY - Distribute only to the container entity feed. The container is specified in the top level containerEntity field and is only valid when containerEntity exists. An example of a container entity feed is the LinkedIn Group feed.Documented type: optional enum</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LearnMarketingCommunityManagementSharesUgcPostApiDistributionFeedDistribution
    {
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAIN_FEED")]
        #pragma warning disable CS1591
        MainFeed,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTAINER_ONLY")]
        #pragma warning disable CS1591
        ContainerOnly,
        #pragma warning restore CS1591
    }
}
