// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LinkedinLiveEventsUgcPostsCreateRequestSpecificContent : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comLinkedinUgcShareContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LinkedinLiveEventsUgcPostsCreateRequestSpecificContentComLinkedinUgcShareContent? ComLinkedinUgcShareContent { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LinkedinLiveEventsUgcPostsCreateRequestSpecificContentComLinkedinUgcShareContent ComLinkedinUgcShareContent { get; set; }
#endif
        /// <summary>The media shared in this share. Can be videos, images, or articles.Documented type: Array of ShareMediaRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharemedia>? Media { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharemedia> Media { get; set; }
#endif
        /// <summary>The main landing page URL of the share. Maximum length is 2000 characters.Documented type: StringRequirement: Optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryLandingPageUrl { get; set; }
#nullable restore
#else
        public string PrimaryLandingPageUrl { get; set; }
#endif
        /// <summary>The message content of this share.Documented type: </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharecontentShareCommentary? ShareCommentary { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharecontentShareCommentary ShareCommentary { get; set; }
#endif
        /// <summary>The type of media contained within the media field of this object. Can be the following enum values: ARTICLE - Content containing articles IMAGE - Content containing images NONE - Content containing media RICH - Content containing rich media VIDEO - Content containing videos LEARNING_COURSE - Content containing learning courses JOB - Content contains jobs QUESTION - Content containing questa questions ANSWER - Content containing questa answers. CAROUSEL - Various types of content rendered in carousel format TOPIC - Content containing topics NATIVE_DOCUMENT - Content file types that are uploaded natively URN_REFERENCE - Media URN for the content category; except when URN type is digital media asset. Use mediaType in ShareMedia when disambiguation is required LIVE_VIDEO - Video content streamed live - ugcPost may be consumed during recording. The resource serving the media is the source of truth for whether the video is currently live.Documented type: Enum stringRequirement: Yes</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharecontentShareMediaCategory? ShareMediaCategory { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.LinkedinLiveEventsUgcPostsCreateRequestSpecificContent"/> and sets the default values.
        /// </summary>
        public LinkedinLiveEventsUgcPostsCreateRequestSpecificContent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.LinkedinLiveEventsUgcPostsCreateRequestSpecificContent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.LinkedinLiveEventsUgcPostsCreateRequestSpecificContent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.LinkedinLiveEventsUgcPostsCreateRequestSpecificContent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "com.linkedin.ugc.ShareContent", n => { ComLinkedinUgcShareContent = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LinkedinLiveEventsUgcPostsCreateRequestSpecificContentComLinkedinUgcShareContent>(global::Soenneker.LinkedIn.OpenApiClient.Models.LinkedinLiveEventsUgcPostsCreateRequestSpecificContentComLinkedinUgcShareContent.CreateFromDiscriminatorValue); } },
                { "media", n => { Media = n.GetCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharemedia>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharemedia.CreateFromDiscriminatorValue)?.AsList(); } },
                { "primaryLandingPageUrl", n => { PrimaryLandingPageUrl = n.GetStringValue(); } },
                { "shareCommentary", n => { ShareCommentary = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharecontentShareCommentary>(global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharecontentShareCommentary.CreateFromDiscriminatorValue); } },
                { "shareMediaCategory", n => { ShareMediaCategory = n.GetEnumValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharecontentShareMediaCategory>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LinkedinLiveEventsUgcPostsCreateRequestSpecificContentComLinkedinUgcShareContent>("com.linkedin.ugc.ShareContent", ComLinkedinUgcShareContent);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharemedia>("media", Media);
            writer.WriteStringValue("primaryLandingPageUrl", PrimaryLandingPageUrl);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharecontentShareCommentary>("shareCommentary", ShareCommentary);
            writer.WriteEnumValue<global::Soenneker.LinkedIn.OpenApiClient.Models.LearnMarketingCommunityManagementSharesUgcPostApiSharecontentShareMediaCategory>("shareMediaCategory", ShareMediaCategory);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
