// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public int? CreatedAt { get; set; }
        /// <summary>The creator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Creator { get; set; }
#nullable restore
#else
        public string Creator { get; set; }
#endif
        /// <summary>The ctvOnly property</summary>
        public bool? CtvOnly { get; set; }
        /// <summary>The currencyCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>The enableAudienceExpansion property</summary>
        public bool? EnableAudienceExpansion { get; set; }
        /// <summary>The enableAudienceNetwork property</summary>
        public bool? EnableAudienceNetwork { get; set; }
        /// <summary>The endDateOn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemEndDateOn? EndDateOn { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemEndDateOn EndDateOn { get; set; }
#endif
        /// <summary>The mediaPlanUrn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaPlanUrn { get; set; }
#nullable restore
#else
        public string MediaPlanUrn { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The objectiveType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectiveType { get; set; }
#nullable restore
#else
        public string ObjectiveType { get; set; }
#endif
        /// <summary>The optimizationType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OptimizationType { get; set; }
#nullable restore
#else
        public string OptimizationType { get; set; }
#endif
        /// <summary>The reachCurve property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemReachCurve? ReachCurve { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemReachCurve ReachCurve { get; set; }
#endif
        /// <summary>The sponsoredAccountUrn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SponsoredAccountUrn { get; set; }
#nullable restore
#else
        public string SponsoredAccountUrn { get; set; }
#endif
        /// <summary>The startDateOn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemStartDateOn? StartDateOn { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemStartDateOn StartDateOn { get; set; }
#endif
        /// <summary>The targetBudgetMicros property</summary>
        public int? TargetBudgetMicros { get; set; }
        /// <summary>The targetingCriteria property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemTargetingCriteria? TargetingCriteria { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemTargetingCriteria TargetingCriteria { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItem"/> and sets the default values.
        /// </summary>
        public MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetIntValue(); } },
                { "creator", n => { Creator = n.GetStringValue(); } },
                { "ctvOnly", n => { CtvOnly = n.GetBoolValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "enableAudienceExpansion", n => { EnableAudienceExpansion = n.GetBoolValue(); } },
                { "enableAudienceNetwork", n => { EnableAudienceNetwork = n.GetBoolValue(); } },
                { "endDateOn", n => { EndDateOn = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemEndDateOn>(global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemEndDateOn.CreateFromDiscriminatorValue); } },
                { "mediaPlanUrn", n => { MediaPlanUrn = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "objectiveType", n => { ObjectiveType = n.GetStringValue(); } },
                { "optimizationType", n => { OptimizationType = n.GetStringValue(); } },
                { "reachCurve", n => { ReachCurve = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemReachCurve>(global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemReachCurve.CreateFromDiscriminatorValue); } },
                { "sponsoredAccountUrn", n => { SponsoredAccountUrn = n.GetStringValue(); } },
                { "startDateOn", n => { StartDateOn = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemStartDateOn>(global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemStartDateOn.CreateFromDiscriminatorValue); } },
                { "targetBudgetMicros", n => { TargetBudgetMicros = n.GetIntValue(); } },
                { "targetingCriteria", n => { TargetingCriteria = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemTargetingCriteria>(global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemTargetingCriteria.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("createdAt", CreatedAt);
            writer.WriteStringValue("creator", Creator);
            writer.WriteBoolValue("ctvOnly", CtvOnly);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteBoolValue("enableAudienceExpansion", EnableAudienceExpansion);
            writer.WriteBoolValue("enableAudienceNetwork", EnableAudienceNetwork);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemEndDateOn>("endDateOn", EndDateOn);
            writer.WriteStringValue("mediaPlanUrn", MediaPlanUrn);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("objectiveType", ObjectiveType);
            writer.WriteStringValue("optimizationType", OptimizationType);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemReachCurve>("reachCurve", ReachCurve);
            writer.WriteStringValue("sponsoredAccountUrn", SponsoredAccountUrn);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemStartDateOn>("startDateOn", StartDateOn);
            writer.WriteIntValue("targetBudgetMicros", TargetBudgetMicros);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.MediaPlanningFetchAllMediaPlansInAnAdAccount200ResponseElementsItemTargetingCriteria>("targetingCriteria", TargetingCriteria);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
