// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8Aef : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The additionalMediaSections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AdditionalMediaSections { get; set; }
#nullable restore
#else
        public UntypedNode AdditionalMediaSections { get; set; }
#endif
        /// <summary>The candidateTestimonialSections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CandidateTestimonialSections { get; set; }
#nullable restore
#else
        public UntypedNode CandidateTestimonialSections { get; set; }
#endif
        /// <summary>The candidateTestimonialSectionsVisible property</summary>
        public bool? CandidateTestimonialSectionsVisible { get; set; }
        /// <summary>The clientTestimonialSections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ClientTestimonialSections { get; set; }
#nullable restore
#else
        public UntypedNode ClientTestimonialSections { get; set; }
#endif
        /// <summary>The clientTestimonialSectionsVisible property</summary>
        public bool? ClientTestimonialSectionsVisible { get; set; }
        /// <summary>The defaultView property</summary>
        public bool? DefaultView { get; set; }
        /// <summary>The featuredMediaSection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefFeaturedMediaSection? FeaturedMediaSection { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefFeaturedMediaSection FeaturedMediaSection { get; set; }
#endif
        /// <summary>The key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The photosSection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefPhotosSection? PhotosSection { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefPhotosSection PhotosSection { get; set; }
#endif
        /// <summary>The reportingId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReportingId { get; set; }
#nullable restore
#else
        public string ReportingId { get; set; }
#endif
        /// <summary>The showLifeAtCulturalInsights property</summary>
        public bool? ShowLifeAtCulturalInsights { get; set; }
        /// <summary>The target property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefTarget? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefTarget Target { get; set; }
#endif
        /// <summary>The testimonialSections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TestimonialSections { get; set; }
#nullable restore
#else
        public UntypedNode TestimonialSections { get; set; }
#endif
        /// <summary>The testimonialSectionsVisible property</summary>
        public bool? TestimonialSectionsVisible { get; set; }
        /// <summary>The vanityName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VanityName { get; set; }
#nullable restore
#else
        public string VanityName { get; set; }
#endif
        /// <summary>The visible property</summary>
        public bool? Visible { get; set; }
        /// <summary>The visibleOnlyWhenTargeted property</summary>
        public bool? VisibleOnlyWhenTargeted { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8Aef"/> and sets the default values.
        /// </summary>
        public PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8Aef()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8Aef"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8Aef CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8Aef();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalMediaSections", n => { AdditionalMediaSections = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "candidateTestimonialSections", n => { CandidateTestimonialSections = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "candidateTestimonialSectionsVisible", n => { CandidateTestimonialSectionsVisible = n.GetBoolValue(); } },
                { "clientTestimonialSections", n => { ClientTestimonialSections = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "clientTestimonialSectionsVisible", n => { ClientTestimonialSectionsVisible = n.GetBoolValue(); } },
                { "defaultView", n => { DefaultView = n.GetBoolValue(); } },
                { "featuredMediaSection", n => { FeaturedMediaSection = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefFeaturedMediaSection>(global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefFeaturedMediaSection.CreateFromDiscriminatorValue); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "photosSection", n => { PhotosSection = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefPhotosSection>(global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefPhotosSection.CreateFromDiscriminatorValue); } },
                { "reportingId", n => { ReportingId = n.GetStringValue(); } },
                { "showLifeAtCulturalInsights", n => { ShowLifeAtCulturalInsights = n.GetBoolValue(); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefTarget>(global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefTarget.CreateFromDiscriminatorValue); } },
                { "testimonialSections", n => { TestimonialSections = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "testimonialSectionsVisible", n => { TestimonialSectionsVisible = n.GetBoolValue(); } },
                { "vanityName", n => { VanityName = n.GetStringValue(); } },
                { "visible", n => { Visible = n.GetBoolValue(); } },
                { "visibleOnlyWhenTargeted", n => { VisibleOnlyWhenTargeted = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("additionalMediaSections", AdditionalMediaSections);
            writer.WriteObjectValue<UntypedNode>("candidateTestimonialSections", CandidateTestimonialSections);
            writer.WriteBoolValue("candidateTestimonialSectionsVisible", CandidateTestimonialSectionsVisible);
            writer.WriteObjectValue<UntypedNode>("clientTestimonialSections", ClientTestimonialSections);
            writer.WriteBoolValue("clientTestimonialSectionsVisible", ClientTestimonialSectionsVisible);
            writer.WriteBoolValue("defaultView", DefaultView);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefFeaturedMediaSection>("featuredMediaSection", FeaturedMediaSection);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefPhotosSection>("photosSection", PhotosSection);
            writer.WriteStringValue("reportingId", ReportingId);
            writer.WriteBoolValue("showLifeAtCulturalInsights", ShowLifeAtCulturalInsights);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsBatchget200ResponseResultsUrnLiOrganizationTargetedContentUrnLiOrganization3811762752C3D33078745DeB71F908800Ef8AefTarget>("target", Target);
            writer.WriteObjectValue<UntypedNode>("testimonialSections", TestimonialSections);
            writer.WriteBoolValue("testimonialSectionsVisible", TestimonialSectionsVisible);
            writer.WriteStringValue("vanityName", VanityName);
            writer.WriteBoolValue("visible", Visible);
            writer.WriteBoolValue("visibleOnlyWhenTargeted", VisibleOnlyWhenTargeted);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
