// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrors : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The urnLiLikeUrnLiPersonFmjIdRRZHeUrnLiActivity7127463160269201408 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiLikeUrnLiPersonFmjIdRrzHeUrnLiActivity7127463160269201408? UrnLiLikeUrnLiPersonFmjIdRRZHeUrnLiActivity7127463160269201408 { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiLikeUrnLiPersonFmjIdRrzHeUrnLiActivity7127463160269201408 UrnLiLikeUrnLiPersonFmjIdRRZHeUrnLiActivity7127463160269201408 { get; set; }
#endif
        /// <summary>The urnLiReactionUrnLiPersonFmjIdRRZHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952? UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952 { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952 UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952 { get; set; }
#endif
        /// <summary>The urnLiReactionUrnLiPersonFmjIdRRZHeUrnLiShare7127705247652745216 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiShare7127705247652745216? UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiShare7127705247652745216 { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiShare7127705247652745216 UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiShare7127705247652745216 { get; set; }
#endif
        /// <summary>The urnLiReactionUrnLiPersonFmjIdRRZHeUrnLiUgcPost7136526602112303104 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiUgcPost7136526602112303104? UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiUgcPost7136526602112303104 { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiUgcPost7136526602112303104 UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiUgcPost7136526602112303104 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrors"/> and sets the default values.
        /// </summary>
        public PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrors()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrors"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrors CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrors();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "urn:li:like:(urn:li:person:fmjIdRRZHe,urn:li:activity:7127463160269201408)", n => { UrnLiLikeUrnLiPersonFmjIdRRZHeUrnLiActivity7127463160269201408 = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiLikeUrnLiPersonFmjIdRrzHeUrnLiActivity7127463160269201408>(global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiLikeUrnLiPersonFmjIdRrzHeUrnLiActivity7127463160269201408.CreateFromDiscriminatorValue); } },
                { "urn:li:reaction:(urn:li:person:fmjIdRRZHe,urn:li:comment:(urn:li:activity:7127705248256724992,7137543297882877952))", n => { UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952 = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952>(global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952.CreateFromDiscriminatorValue); } },
                { "urn:li:reaction:(urn:li:person:fmjIdRRZHe,urn:li:share:7127705247652745216)", n => { UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiShare7127705247652745216 = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiShare7127705247652745216>(global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiShare7127705247652745216.CreateFromDiscriminatorValue); } },
                { "urn:li:reaction:(urn:li:person:fmjIdRRZHe,urn:li:ugcPost:7136526602112303104)", n => { UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiUgcPost7136526602112303104 = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiUgcPost7136526602112303104>(global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiUgcPost7136526602112303104.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiLikeUrnLiPersonFmjIdRrzHeUrnLiActivity7127463160269201408>("urn:li:like:(urn:li:person:fmjIdRRZHe,urn:li:activity:7127463160269201408)", UrnLiLikeUrnLiPersonFmjIdRRZHeUrnLiActivity7127463160269201408);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952>("urn:li:reaction:(urn:li:person:fmjIdRRZHe,urn:li:comment:(urn:li:activity:7127705248256724992,7137543297882877952))", UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiCommentUrnLiActivity71277052482567249927137543297882877952);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiShare7127705247652745216>("urn:li:reaction:(urn:li:person:fmjIdRRZHe,urn:li:share:7127705247652745216)", UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiShare7127705247652745216);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaReactionsBatchget2001OptInReactionUrnPersonUrnOnPageActivity200ResponseErrorsUrnLiReactionUrnLiPersonFmjIdRrzHeUrnLiUgcPost7136526602112303104>("urn:li:reaction:(urn:li:person:fmjIdRRZHe,urn:li:ugcPost:7136526602112303104)", UrnLiReactionUrnLiPersonFmjIdRRZHeUrnLiUgcPost7136526602112303104);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
