// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PagesDataPortabilityDmaOrganizationalPageProfilesGet200ResponsePageProfileEntityCombinedOrganizationProductPage : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents the viewability of the combined organization and product page entity relationship in the member experience. Value enums include COMBINEDORGANIZATIONDocumented type: CombinedOrganizationProductPageEntityMemberExperienceViewableStateRequirement: Yes</summary>
        public global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationalPageProfilesGet200ResponsePageProfileEntityCombinedOrganizationProductPageMemberExperienceViewableState? MemberExperienceViewableState { get; set; }
        /// <summary>Denotes a product.Documented type: StandardizedProductUrnRequirement: Yes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StandardizedProduct { get; set; }
#nullable restore
#else
        public string StandardizedProduct { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationalPageProfilesGet200ResponsePageProfileEntityCombinedOrganizationProductPage"/> and sets the default values.
        /// </summary>
        public PagesDataPortabilityDmaOrganizationalPageProfilesGet200ResponsePageProfileEntityCombinedOrganizationProductPage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationalPageProfilesGet200ResponsePageProfileEntityCombinedOrganizationProductPage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationalPageProfilesGet200ResponsePageProfileEntityCombinedOrganizationProductPage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationalPageProfilesGet200ResponsePageProfileEntityCombinedOrganizationProductPage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "memberExperienceViewableState", n => { MemberExperienceViewableState = n.GetEnumValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationalPageProfilesGet200ResponsePageProfileEntityCombinedOrganizationProductPageMemberExperienceViewableState>(); } },
                { "standardizedProduct", n => { StandardizedProduct = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationalPageProfilesGet200ResponsePageProfileEntityCombinedOrganizationProductPageMemberExperienceViewableState>("memberExperienceViewableState", MemberExperienceViewableState);
            writer.WriteStringValue("standardizedProduct", StandardizedProduct);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
