// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    /// <summary>The topic of the PagesFeaturedContent. Value enums include: PRODUCT_HIGHLIGHTSPRODUCT_ANNOUNCEMENTSPRODUCT_EXPERTSPRODUCT_QUESTIONS_AND_ANSWERSORGANIZATION_HOMEDocumented type: PagesFeaturedContentTopicRequirement: Yes</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PagesDataPortabilityDmaPagesFeaturedContentGroupsBatchget200ResponseResultsPageUrn3Ali3AorganizationalPage3A2414183TopicOrganizationHomeKeyTopic
    {
        [EnumMember(Value = "PRODUCT_HIGHLIGHTS")]
        #pragma warning disable CS1591
        ProductHighlights,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCT_ANNOUNCEMENTS")]
        #pragma warning disable CS1591
        ProductAnnouncements,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCT_EXPERTS")]
        #pragma warning disable CS1591
        ProductExperts,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCT_QUESTIONS_AND_ANSWERS")]
        #pragma warning disable CS1591
        ProductQuestionsAndAnswers,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORGANIZATION_HOME")]
        #pragma warning disable CS1591
        OrganizationHome,
        #pragma warning restore CS1591
    }
}
