// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTarget : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The geoLocations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? GeoLocations { get; set; }
#nullable restore
#else
        public List<string> GeoLocations { get; set; }
#endif
        /// <summary>The industries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Industries { get; set; }
#nullable restore
#else
        public List<string> Industries { get; set; }
#endif
        /// <summary>The interfaceLocales property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTargetInterfaceLocalesItem>? InterfaceLocales { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTargetInterfaceLocalesItem> InterfaceLocales { get; set; }
#endif
        /// <summary>The jobFunctions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? JobFunctions { get; set; }
#nullable restore
#else
        public List<string> JobFunctions { get; set; }
#endif
        /// <summary>The locations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Locations { get; set; }
#nullable restore
#else
        public List<string> Locations { get; set; }
#endif
        /// <summary>The seniorities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Seniorities { get; set; }
#nullable restore
#else
        public List<string> Seniorities { get; set; }
#endif
        /// <summary>The staffCountRanges property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StaffCountRanges { get; set; }
#nullable restore
#else
        public List<string> StaffCountRanges { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTarget"/> and sets the default values.
        /// </summary>
        public PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTarget()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTarget"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTarget CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTarget();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "geoLocations", n => { GeoLocations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "industries", n => { Industries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "interfaceLocales", n => { InterfaceLocales = n.GetCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTargetInterfaceLocalesItem>(global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTargetInterfaceLocalesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "jobFunctions", n => { JobFunctions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "locations", n => { Locations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "seniorities", n => { Seniorities = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "staffCountRanges", n => { StaffCountRanges = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("geoLocations", GeoLocations);
            writer.WriteCollectionOfPrimitiveValues<string>("industries", Industries);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.PagesDataPortabilityDmaOrganizationTargetedContentsGet200ResponseTargetInterfaceLocalesItem>("interfaceLocales", InterfaceLocales);
            writer.WriteCollectionOfPrimitiveValues<string>("jobFunctions", JobFunctions);
            writer.WriteCollectionOfPrimitiveValues<string>("locations", Locations);
            writer.WriteCollectionOfPrimitiveValues<string>("seniorities", Seniorities);
            writer.WriteCollectionOfPrimitiveValues<string>("staffCountRanges", StaffCountRanges);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
