// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecruiterSystemConnectVersionedCreateJobRequisitionStagesJsonRequestAnyOf2EntitiesJobRequisitionStageIdStage12345JobRequisitionIdReq67890IntegrationContextUrnLiOrganization1234567890 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Time at which the stage was created in the partner system. This is epoch timestamp in milliseconds (UTC) and should not be a future time.Documented type: UTC Epoch MillisecondsRequirement: Required</summary>
        public long? ExternalCreatedAt { get; set; }
        /// <summary>Time at which the stage was last modified in the partner system. This is epoch timestamp in milliseconds (UTC) and should not be a future timeDocumented type: UTC Epoch MillisecondsRequirement: Required</summary>
        public long? ExternalLastModifiedAt { get; set; }
        /// <summary>Name of the stage in partner system.Documented type: StringRequirement: Required</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StageName { get; set; }
#nullable restore
#else
        public string StageName { get; set; }
#endif
        /// <summary>Order/Sequence of the stage in job requisition pipeline in partner system.Documented type: IntegerRequirement: Required</summary>
        public int? StageOrder { get; set; }
        /// <summary>Status of job requisition stage. Available options are: ACTIVE, INACTIVE. Default value is ACTIVE if not applicable.Documented type: StringRequirement: Optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StageStatus { get; set; }
#nullable restore
#else
        public string StageStatus { get; set; }
#endif
        /// <summary>This denotes the “type” of stage. Eg. is it a pre_application stage, interview stage etc. This should be provided if partner&apos;s stageName can be grouped into one of the provided options. Available options are: PRE_APPLICATION, CONTACTED, APPLIED, SCREEN, INTERVIEW, REFERENCE_CHECK, OFFER, PRE_HIRE, HIRED, DISPOSITIONED, SHORTLISTED, HIRING_MANAGER_REVIEW, UNKNOWN. Default value is UNKNOWN if not applicable.Documented type: StringRequirement: Optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StageType { get; set; }
#nullable restore
#else
        public string StageType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedCreateJobRequisitionStagesJsonRequestAnyOf2EntitiesJobRequisitionStageIdStage12345JobRequisitionIdReq67890IntegrationContextUrnLiOrganization1234567890"/> and sets the default values.
        /// </summary>
        public RecruiterSystemConnectVersionedCreateJobRequisitionStagesJsonRequestAnyOf2EntitiesJobRequisitionStageIdStage12345JobRequisitionIdReq67890IntegrationContextUrnLiOrganization1234567890()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedCreateJobRequisitionStagesJsonRequestAnyOf2EntitiesJobRequisitionStageIdStage12345JobRequisitionIdReq67890IntegrationContextUrnLiOrganization1234567890"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedCreateJobRequisitionStagesJsonRequestAnyOf2EntitiesJobRequisitionStageIdStage12345JobRequisitionIdReq67890IntegrationContextUrnLiOrganization1234567890 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedCreateJobRequisitionStagesJsonRequestAnyOf2EntitiesJobRequisitionStageIdStage12345JobRequisitionIdReq67890IntegrationContextUrnLiOrganization1234567890();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "externalCreatedAt", n => { ExternalCreatedAt = n.GetLongValue(); } },
                { "externalLastModifiedAt", n => { ExternalLastModifiedAt = n.GetLongValue(); } },
                { "stageName", n => { StageName = n.GetStringValue(); } },
                { "stageOrder", n => { StageOrder = n.GetIntValue(); } },
                { "stageStatus", n => { StageStatus = n.GetStringValue(); } },
                { "stageType", n => { StageType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("externalCreatedAt", ExternalCreatedAt);
            writer.WriteLongValue("externalLastModifiedAt", ExternalLastModifiedAt);
            writer.WriteStringValue("stageName", StageName);
            writer.WriteIntValue("stageOrder", StageOrder);
            writer.WriteStringValue("stageStatus", StageStatus);
            writer.WriteStringValue("stageType", StageType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
