// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntities : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The integrationContextUrnLiContractContract_idIntegrationTypeCSA_APITenantTypeRECRUITER property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiContractContractIdIntegrationTypeCsaApiTenantTypeRecruiter? IntegrationContextUrnLiContractContractIdIntegrationTypeCSAAPITenantTypeRECRUITER { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiContractContractIdIntegrationTypeCsaApiTenantTypeRecruiter IntegrationContextUrnLiContractContractIdIntegrationTypeCSAAPITenantTypeRECRUITER { get; set; }
#endif
        /// <summary>The integrationContextUrnLiOrganizationOrg_idIntegrationTypeIN_ATS_INDICATORTenantTypeRECRUITER property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeInAtsIndicatorTenantTypeRecruiter? IntegrationContextUrnLiOrganizationOrgIdIntegrationTypeINATSINDICATORTenantTypeRECRUITER { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeInAtsIndicatorTenantTypeRecruiter IntegrationContextUrnLiOrganizationOrgIdIntegrationTypeINATSINDICATORTenantTypeRECRUITER { get; set; }
#endif
        /// <summary>The integrationContextUrnLiOrganizationOrg_idIntegrationTypeONE_CLICK_EXPORTTenantTypeRECRUITER property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeOneClickExportTenantTypeRecruiter? IntegrationContextUrnLiOrganizationOrgIdIntegrationTypeONECLICKEXPORTTenantTypeRECRUITER { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeOneClickExportTenantTypeRecruiter IntegrationContextUrnLiOrganizationOrgIdIntegrationTypeONECLICKEXPORTTenantTypeRECRUITER { get; set; }
#endif
        /// <summary>The integrationContextUrnLiOrganizationOrg_idIntegrationTypePROFILE_PLUGINTenantTypeRECRUITER property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeProfilePluginTenantTypeRecruiter? IntegrationContextUrnLiOrganizationOrgIdIntegrationTypePROFILEPLUGINTenantTypeRECRUITER { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeProfilePluginTenantTypeRecruiter IntegrationContextUrnLiOrganizationOrgIdIntegrationTypePROFILEPLUGINTenantTypeRECRUITER { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntities"/> and sets the default values.
        /// </summary>
        public RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntities()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntities"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntities CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntities();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "integrationContext=urn:li:contract:{{contract_id}}&integrationType=CSA_API&tenantType=RECRUITER", n => { IntegrationContextUrnLiContractContractIdIntegrationTypeCSAAPITenantTypeRECRUITER = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiContractContractIdIntegrationTypeCsaApiTenantTypeRecruiter>(global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiContractContractIdIntegrationTypeCsaApiTenantTypeRecruiter.CreateFromDiscriminatorValue); } },
                { "integrationContext=urn:li:organization:{{org_id}}&integrationType=IN_ATS_INDICATOR&tenantType=RECRUITER", n => { IntegrationContextUrnLiOrganizationOrgIdIntegrationTypeINATSINDICATORTenantTypeRECRUITER = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeInAtsIndicatorTenantTypeRecruiter>(global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeInAtsIndicatorTenantTypeRecruiter.CreateFromDiscriminatorValue); } },
                { "integrationContext=urn:li:organization:{{org_id}}&integrationType=ONE_CLICK_EXPORT&tenantType=RECRUITER", n => { IntegrationContextUrnLiOrganizationOrgIdIntegrationTypeONECLICKEXPORTTenantTypeRECRUITER = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeOneClickExportTenantTypeRecruiter>(global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeOneClickExportTenantTypeRecruiter.CreateFromDiscriminatorValue); } },
                { "integrationContext=urn:li:organization:{{org_id}}&integrationType=PROFILE_PLUGIN&tenantType=RECRUITER", n => { IntegrationContextUrnLiOrganizationOrgIdIntegrationTypePROFILEPLUGINTenantTypeRECRUITER = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeProfilePluginTenantTypeRecruiter>(global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeProfilePluginTenantTypeRecruiter.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiContractContractIdIntegrationTypeCsaApiTenantTypeRecruiter>("integrationContext=urn:li:contract:{{contract_id}}&integrationType=CSA_API&tenantType=RECRUITER", IntegrationContextUrnLiContractContractIdIntegrationTypeCSAAPITenantTypeRECRUITER);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeInAtsIndicatorTenantTypeRecruiter>("integrationContext=urn:li:organization:{{org_id}}&integrationType=IN_ATS_INDICATOR&tenantType=RECRUITER", IntegrationContextUrnLiOrganizationOrgIdIntegrationTypeINATSINDICATORTenantTypeRECRUITER);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeOneClickExportTenantTypeRecruiter>("integrationContext=urn:li:organization:{{org_id}}&integrationType=ONE_CLICK_EXPORT&tenantType=RECRUITER", IntegrationContextUrnLiOrganizationOrgIdIntegrationTypeONECLICKEXPORTTenantTypeRECRUITER);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.RecruiterSystemConnectVersionedUpdateCustomerAtsIntegrationRequestEntitiesIntegrationContextUrnLiOrganizationOrgIdIntegrationTypeProfilePluginTenantTypeRecruiter>("integrationContext=urn:li:organization:{{org_id}}&integrationType=PROFILE_PLUGIN&tenantType=RECRUITER", IntegrationContextUrnLiOrganizationOrgIdIntegrationTypePROFILEPLUGINTenantTypeRECRUITER);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
