// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The approximateUniqueImpressions property</summary>
        public long? ApproximateUniqueImpressions { get; set; }
        /// <summary>The clicks property</summary>
        public long? Clicks { get; set; }
        /// <summary>The comments property</summary>
        public long? Comments { get; set; }
        /// <summary>The conversionValueInLocalCurrency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversionValueInLocalCurrency { get; set; }
#nullable restore
#else
        public string ConversionValueInLocalCurrency { get; set; }
#endif
        /// <summary>The costInLocalCurrency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CostInLocalCurrency { get; set; }
#nullable restore
#else
        public string CostInLocalCurrency { get; set; }
#endif
        /// <summary>The costInUsd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CostInUsd { get; set; }
#nullable restore
#else
        public string CostInUsd { get; set; }
#endif
        /// <summary>The dateRange property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemDateRange? DateRange { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemDateRange DateRange { get; set; }
#endif
        /// <summary>The externalWebsiteConversions property</summary>
        public long? ExternalWebsiteConversions { get; set; }
        /// <summary>The externalWebsitePostClickConversions property</summary>
        public long? ExternalWebsitePostClickConversions { get; set; }
        /// <summary>The externalWebsitePostViewConversions property</summary>
        public long? ExternalWebsitePostViewConversions { get; set; }
        /// <summary>The follows property</summary>
        public long? Follows { get; set; }
        /// <summary>The impressions property</summary>
        public long? Impressions { get; set; }
        /// <summary>The landingPageClicks property</summary>
        public long? LandingPageClicks { get; set; }
        /// <summary>The likes property</summary>
        public long? Likes { get; set; }
        /// <summary>The oneClickLeadFormOpens property</summary>
        public long? OneClickLeadFormOpens { get; set; }
        /// <summary>The oneClickLeads property</summary>
        public long? OneClickLeads { get; set; }
        /// <summary>The opens property</summary>
        public long? Opens { get; set; }
        /// <summary>The pivot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pivot { get; set; }
#nullable restore
#else
        public string Pivot { get; set; }
#endif
        /// <summary>The pivotValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PivotValue { get; set; }
#nullable restore
#else
        public string PivotValue { get; set; }
#endif
        /// <summary>The pivotValues property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PivotValues { get; set; }
#nullable restore
#else
        public List<string> PivotValues { get; set; }
#endif
        /// <summary>The reactions property</summary>
        public long? Reactions { get; set; }
        /// <summary>The pivotValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValue? ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValue { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValue ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValue { get; set; }
#endif
        /// <summary>The pivotValues property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValuesItem>? ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValues { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValuesItem> ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValues { get; set; }
#endif
        /// <summary>The revenueAttributionMetrics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemRevenueAttributionMetrics? RevenueAttributionMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemRevenueAttributionMetrics RevenueAttributionMetrics { get; set; }
#endif
        /// <summary>The sends property</summary>
        public long? Sends { get; set; }
        /// <summary>The shares property</summary>
        public long? Shares { get; set; }
        /// <summary>The totalEngagements property</summary>
        public long? TotalEngagements { get; set; }
        /// <summary>The videoCompletions property</summary>
        public long? VideoCompletions { get; set; }
        /// <summary>The videoViews property</summary>
        public long? VideoViews { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItem"/> and sets the default values.
        /// </summary>
        public ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approximateUniqueImpressions", n => { ApproximateUniqueImpressions = n.GetLongValue(); } },
                { "clicks", n => { Clicks = n.GetLongValue(); } },
                { "comments", n => { Comments = n.GetLongValue(); } },
                { "conversionValueInLocalCurrency", n => { ConversionValueInLocalCurrency = n.GetStringValue(); } },
                { "costInLocalCurrency", n => { CostInLocalCurrency = n.GetStringValue(); } },
                { "costInUsd", n => { CostInUsd = n.GetStringValue(); } },
                { "dateRange", n => { DateRange = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemDateRange>(global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemDateRange.CreateFromDiscriminatorValue); } },
                { "externalWebsiteConversions", n => { ExternalWebsiteConversions = n.GetLongValue(); } },
                { "externalWebsitePostClickConversions", n => { ExternalWebsitePostClickConversions = n.GetLongValue(); } },
                { "externalWebsitePostViewConversions", n => { ExternalWebsitePostViewConversions = n.GetLongValue(); } },
                { "follows", n => { Follows = n.GetLongValue(); } },
                { "impressions", n => { Impressions = n.GetLongValue(); } },
                { "landingPageClicks", n => { LandingPageClicks = n.GetLongValue(); } },
                { "likes", n => { Likes = n.GetLongValue(); } },
                { "oneClickLeadFormOpens", n => { OneClickLeadFormOpens = n.GetLongValue(); } },
                { "oneClickLeads", n => { OneClickLeads = n.GetLongValue(); } },
                { "opens", n => { Opens = n.GetLongValue(); } },
                { "pivot", n => { Pivot = n.GetStringValue(); } },
                { "pivotValue", n => { PivotValue = n.GetStringValue(); } },
                { "pivotValues", n => { PivotValues = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "reactions", n => { Reactions = n.GetLongValue(); } },
                { "pivotValue~", n => { ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValue = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValue>(global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValue.CreateFromDiscriminatorValue); } },
                { "pivotValues~", n => { ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValues = n.GetCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValuesItem>(global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValuesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "revenueAttributionMetrics", n => { RevenueAttributionMetrics = n.GetObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemRevenueAttributionMetrics>(global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemRevenueAttributionMetrics.CreateFromDiscriminatorValue); } },
                { "sends", n => { Sends = n.GetLongValue(); } },
                { "shares", n => { Shares = n.GetLongValue(); } },
                { "totalEngagements", n => { TotalEngagements = n.GetLongValue(); } },
                { "videoCompletions", n => { VideoCompletions = n.GetLongValue(); } },
                { "videoViews", n => { VideoViews = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("approximateUniqueImpressions", ApproximateUniqueImpressions);
            writer.WriteLongValue("clicks", Clicks);
            writer.WriteLongValue("comments", Comments);
            writer.WriteStringValue("conversionValueInLocalCurrency", ConversionValueInLocalCurrency);
            writer.WriteStringValue("costInLocalCurrency", CostInLocalCurrency);
            writer.WriteStringValue("costInUsd", CostInUsd);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemDateRange>("dateRange", DateRange);
            writer.WriteLongValue("externalWebsiteConversions", ExternalWebsiteConversions);
            writer.WriteLongValue("externalWebsitePostClickConversions", ExternalWebsitePostClickConversions);
            writer.WriteLongValue("externalWebsitePostViewConversions", ExternalWebsitePostViewConversions);
            writer.WriteLongValue("follows", Follows);
            writer.WriteLongValue("impressions", Impressions);
            writer.WriteLongValue("landingPageClicks", LandingPageClicks);
            writer.WriteLongValue("likes", Likes);
            writer.WriteLongValue("oneClickLeadFormOpens", OneClickLeadFormOpens);
            writer.WriteLongValue("oneClickLeads", OneClickLeads);
            writer.WriteLongValue("opens", Opens);
            writer.WriteStringValue("pivot", Pivot);
            writer.WriteStringValue("pivotValue", PivotValue);
            writer.WriteCollectionOfPrimitiveValues<string>("pivotValues", PivotValues);
            writer.WriteLongValue("reactions", Reactions);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValue>("pivotValue~", ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValue);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValuesItem>("pivotValues~", ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemPivotValues);
            writer.WriteObjectValue<global::Soenneker.LinkedIn.OpenApiClient.Models.ReportingRoiByCreativeCampaignWithCreativeTypeStatusCampaignNameTypeStatusCampaignGroupProjection200ResponseElementsItemRevenueAttributionMetrics>("revenueAttributionMetrics", RevenueAttributionMetrics);
            writer.WriteLongValue("sends", Sends);
            writer.WriteLongValue("shares", Shares);
            writer.WriteLongValue("totalEngagements", TotalEngagements);
            writer.WriteLongValue("videoCompletions", VideoCompletions);
            writer.WriteLongValue("videoViews", VideoViews);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
