// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.LinkedIn.OpenApiClient.CompanyIntelligenceApi.AdAccounts.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.LinkedIn.OpenApiClient.CompanyIntelligenceApi.AdAccounts
{
    /// <summary>
    /// Builds and executes requests for operations under \company-intelligence-api\adAccounts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdAccountsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.LinkedIn.OpenApiClient.companyIntelligenceApi.adAccounts.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.LinkedIn.OpenApiClient.CompanyIntelligenceApi.AdAccounts.Item.WithAdAccountsItemRequestBuilder"/></returns>
        public global::Soenneker.LinkedIn.OpenApiClient.CompanyIntelligenceApi.AdAccounts.Item.WithAdAccountsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("adAccountsId", position);
                return new global::Soenneker.LinkedIn.OpenApiClient.CompanyIntelligenceApi.AdAccounts.Item.WithAdAccountsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.CompanyIntelligenceApi.AdAccounts.AdAccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdAccountsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/company-intelligence-api/adAccounts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LinkedIn.OpenApiClient.CompanyIntelligenceApi.AdAccounts.AdAccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdAccountsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/company-intelligence-api/adAccounts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
